name: Update Gold Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-gold:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Get Gold OHLC data
        env:
          GOLD_API_KEY: ${{ secrets.GOLD_API_KEY }}
        run: |
          curl -L \
            -H "x-api-key: $GOLD_API_KEY" \
            "https://api.gold-api.com/ohlc/XAU" \
            -o market-data.json

      - name: Save data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add market-data.json
          git diff --cached --quiet || git commit -m "Update gold market data"
          git push
